# Request
int32 robot_id      # ID of the robot requesting registration
---
# Response
bool success        # Whether registration was successful
string message      # Additional information or error message