# default value (used while not declared)
latency_values: [0.0, 1.0]
iterations_per_latency: 20
timeout_seconds: 300.0

test_scenarios:
  - name: "test_data_new"
    map_path: "data/test_data_new/map.json"
    graph_path: "data/test_data_new/graph.json"
    robot_start_path: "data/test_data_new/robot_start.json"
    robot_spec_path: "data/test_data_new/schedule.csv"
    world_file: "test_data_new.world"
    rviz_config_path: "src/obj_robot_visualizer/config/test_data_new.rviz"
    latency_values: [0.0]
    iterations_per_latency: 1
    timeout_seconds: 150.0

  - name: "test_data_cross"
    map_path: "data/test_data_cross/map.json"
    graph_path: "data/test_data_cross/graph.json"
    robot_start_path: "data/test_data_cross/robot_start.json"
    robot_spec_path: "data/test_data_cross/schedule.csv"
    world_file: "test_data_cross.world"
    rviz_config_path: "src/obj_robot_visualizer/config/test_data_cross.rviz"
    latency_values: [0.0]
    iterations_per_latency: 1
    timeout_seconds: 150.0
  
  - name: "test_data"
    map_path: "data/test_data/map.json"
    graph_path: "data/test_data/graph.json"
    robot_start_path: "data/test_data/robot_start.json"
    robot_spec_path: "data/test_data/schedule.csv"
    world_file: "test_data.world"
    rviz_config_path: "src/obj_robot_visualizer/config/test_data.rviz"
    latency_values: [0.0, 1.0]
    iterations_per_latency: 1
    timeout_seconds: 150.0